/**
 * HireSense-AI — ATS Analysis Report Page
 * Full breakdown of the resume analysis results.
 */
import { useEffect, useState } from 'react'
import { useParams, useLocation, useNavigate, Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import {
  RadarChart, PolarGrid, PolarAngleAxis, Radar, ResponsiveContainer,
  BarChart, Bar, XAxis, YAxis, Tooltip, Cell,
} from 'recharts'
import {
  Download, ArrowLeft, AlertTriangle, CheckCircle, Lightbulb,
  Zap, Target, BookOpen, TrendingUp, RefreshCw
} from 'lucide-react'
import api from '../utils/api'
import ScoreRing from '../components/ScoreRing'
import ScoreBar from '../components/ScoreBar'
import SectionCard from '../components/SectionCard'
import { KeywordBadge, SkillBadge } from '../components/KeywordBadge'
import { getScoreColor, formatDate } from '../utils/helpers'
import toast from 'react-hot-toast'

export default function Report() {
  const { id } = useParams()
  const { state } = useLocation()
  const navigate = useNavigate()

  const [report, setReport] = useState(state?.report || null)
  const [loading, setLoading] = useState(!state?.report)

  useEffect(() => {
    if (!report) {
      api.get(`/api/resume/report/${id}`)
        .then(res => setReport(res.data))
        .catch(() => { toast.error('Report not found.'); navigate('/history') })
        .finally(() => setLoading(false))
    }
  }, [id])

  if (loading) return (
    <div className="min-h-screen flex items-center justify-center">
      <div className="w-8 h-8 border-2 border-brand-500 border-t-transparent rounded-full animate-spin" />
    </div>
  )

  if (!report) return null

  // Prepare chart data
  const radarData = [
    { subject: 'ATS', value: report.ats_score },
    { subject: 'Keywords', value: report.keyword_score },
    { subject: 'Format', value: report.format_score },
    { subject: 'Readability', value: report.readability_score },
  ]

  const barData = Object.entries(report.section_analysis || {}).map(([name, data]) => ({
    name: name.charAt(0).toUpperCase() + name.slice(1),
    score: data?.score || 0,
  }))

  const handleDownload = () => {
    const text = `
HireSense-AI — Resume Analysis Report
======================================
File: ${report.filename}
Role: ${report.job_role}
Date: ${formatDate(report.created_at)}

SCORES
------
ATS Score: ${report.ats_score}/100
Keyword Score: ${report.keyword_score}/100
Format Score: ${report.format_score}/100
Readability Score: ${report.readability_score}/100

OVERALL ASSESSMENT
------------------
${report.overall_assessment}

FOUND KEYWORDS
--------------
${(report.found_keywords || []).join(', ')}

MISSING KEYWORDS
----------------
${(report.missing_keywords || []).join(', ')}

SKILLS TO ADD
-------------
${(report.skills_to_add || []).join(', ')}

SUGGESTIONS
-----------
${(report.suggestions || []).map((s, i) => `${i+1}. ${s}`).join('\n')}

IMPROVED SUMMARY
----------------
${report.improved_summary}

WEAK ACTION VERBS
-----------------
${(report.weak_verbs || []).map(v => `"${v.original}" → "${v.better}"`).join('\n')}

Generated by HireSense-AI
    `.trim()

    const blob = new Blob([text], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `hiresense-report-${id}.txt`
    a.click()
    URL.revokeObjectURL(url)
    toast.success('Report downloaded!')
  }

  return (
    <div className="min-h-screen px-4 py-12">
      <div className="max-w-6xl mx-auto">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: -10 }}
          animate={{ opacity: 1, y: 0 }}
          className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-10"
        >
          <div>
            <Link to="/history" className="flex items-center gap-2 text-sm text-slate-400 hover:text-brand-400 transition-colors mb-3">
              <ArrowLeft size={14} /> Back to History
            </Link>
            <h1 className="font-display font-bold text-3xl gradient-text">Analysis Report</h1>
            <p className="text-slate-400 text-sm mt-1">
              {report.filename} · {report.job_role} · {formatDate(report.created_at)}
            </p>
          </div>
          <div className="flex gap-3">
            <Link to="/upload" className="btn-secondary flex items-center gap-2 text-sm py-2.5 px-4">
              <RefreshCw size={15} /> New Analysis
            </Link>
            <button onClick={handleDownload} className="btn-primary flex items-center gap-2 text-sm py-2.5 px-4">
              <Download size={15} /> Download
            </button>
          </div>
        </motion.div>

        {/* ── Score Overview ─────────────────────────────────── */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="glass rounded-2xl p-8 border border-white/10 mb-6"
        >
          <h2 className="font-display font-semibold text-xl mb-6">Score Dashboard</h2>
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-8">
            <ScoreRing score={Math.round(report.ats_score)} label="ATS Score" />
            <ScoreRing score={Math.round(report.keyword_score)} label="Keywords" size={140} strokeWidth={9} />
            <ScoreRing score={Math.round(report.format_score)} label="Format" size={140} strokeWidth={9} />
            <ScoreRing score={Math.round(report.readability_score)} label="Readability" size={140} strokeWidth={9} />
          </div>
        </motion.div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-6">
          {/* Radar Chart */}
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.2 }}
            className="glass rounded-2xl p-6 border border-white/10"
          >
            <h2 className="font-display font-semibold text-lg mb-4">Score Radar</h2>
            <ResponsiveContainer width="100%" height={220}>
              <RadarChart data={radarData}>
                <PolarGrid stroke="rgba(255,255,255,0.05)" />
                <PolarAngleAxis dataKey="subject" tick={{ fill: '#94a3b8', fontSize: 12 }} />
                <Radar
                  name="Score"
                  dataKey="value"
                  stroke="#3371ff"
                  fill="#3371ff"
                  fillOpacity={0.2}
                  strokeWidth={2}
                />
              </RadarChart>
            </ResponsiveContainer>
          </motion.div>

          {/* Score Bars */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.25 }}
            className="glass rounded-2xl p-6 border border-white/10"
          >
            <h2 className="font-display font-semibold text-lg mb-4">Score Breakdown</h2>
            <div className="space-y-4">
              <ScoreBar label="ATS Compatibility" score={Math.round(report.ats_score)} delay={0.3} />
              <ScoreBar label="Keyword Match" score={Math.round(report.keyword_score)} delay={0.4} />
              <ScoreBar label="Format Quality" score={Math.round(report.format_score)} delay={0.5} />
              <ScoreBar label="Readability" score={Math.round(report.readability_score)} delay={0.6} />
            </div>
          </motion.div>

          {/* Section Bar Chart */}
          <motion.div
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.3 }}
            className="glass rounded-2xl p-6 border border-white/10"
          >
            <h2 className="font-display font-semibold text-lg mb-4">Sections</h2>
            <ResponsiveContainer width="100%" height={220}>
              <BarChart data={barData} layout="vertical" barSize={10}>
                <XAxis type="number" domain={[0, 100]} tick={{ fill: '#94a3b8', fontSize: 11 }} />
                <YAxis type="category" dataKey="name" tick={{ fill: '#94a3b8', fontSize: 11 }} width={75} />
                <Tooltip
                  contentStyle={{ background: '#0f172a', border: '1px solid rgba(51,113,255,0.2)', borderRadius: 8 }}
                  labelStyle={{ color: '#e2e8f0' }}
                />
                <Bar dataKey="score" radius={[0, 5, 5, 0]}>
                  {barData.map((entry, i) => (
                    <Cell key={i} fill={getScoreColor(entry.score)} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </motion.div>
        </div>

        {/* ── Overall Assessment ─────────────────────────────── */}
        {report.overall_assessment && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.35 }}
            className="glass rounded-2xl p-6 border border-brand-500/20 bg-brand-500/5 mb-6"
          >
            <div className="flex items-start gap-3">
              <div className="w-8 h-8 rounded-lg bg-brand-500/20 flex items-center justify-center shrink-0 mt-0.5">
                <BookOpen size={16} className="text-brand-400" />
              </div>
              <div>
                <h2 className="font-display font-semibold text-lg text-brand-300 mb-2">Overall Assessment</h2>
                <p className="text-slate-300 text-sm leading-relaxed">{report.overall_assessment}</p>
              </div>
            </div>
          </motion.div>
        )}

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-6">
          {/* Found Keywords */}
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.4 }}
            className="glass rounded-2xl p-6 border border-white/10"
          >
            <div className="flex items-center gap-2 mb-4">
              <CheckCircle size={18} className="text-emerald-400" />
              <h2 className="font-display font-semibold text-lg">Found Keywords ({report.found_keywords?.length || 0})</h2>
            </div>
            <div className="flex flex-wrap gap-2">
              {(report.found_keywords || []).map((kw, i) => (
                <KeywordBadge key={kw} keyword={kw} found={true} index={i} />
              ))}
              {!report.found_keywords?.length && (
                <p className="text-slate-500 text-sm">No matching keywords found.</p>
              )}
            </div>
          </motion.div>

          {/* Missing Keywords */}
          <motion.div
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.4 }}
            className="glass rounded-2xl p-6 border border-white/10"
          >
            <div className="flex items-center gap-2 mb-4">
              <AlertTriangle size={18} className="text-amber-400" />
              <h2 className="font-display font-semibold text-lg">Missing Keywords ({report.missing_keywords?.length || 0})</h2>
            </div>
            <div className="flex flex-wrap gap-2">
              {(report.missing_keywords || []).map((kw, i) => (
                <KeywordBadge key={kw} keyword={kw} found={false} index={i} />
              ))}
              {!report.missing_keywords?.length && (
                <p className="text-slate-500 text-sm">Great! No critical keywords missing.</p>
              )}
            </div>
          </motion.div>
        </div>

        {/* ── Suggestions ─────────────────────────────────────── */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.45 }}
          className="glass rounded-2xl p-6 border border-white/10 mb-6"
        >
          <div className="flex items-center gap-2 mb-5">
            <Lightbulb size={18} className="text-amber-400" />
            <h2 className="font-display font-semibold text-xl">Improvement Suggestions</h2>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {(report.suggestions || []).map((s, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.45 + i * 0.05 }}
                className="flex items-start gap-3 glass rounded-xl p-4"
              >
                <span className="text-xs font-mono text-brand-400 shrink-0 mt-0.5">{String(i+1).padStart(2,'0')}</span>
                <p className="text-sm text-slate-300 leading-relaxed">{s}</p>
              </motion.div>
            ))}
          </div>
        </motion.div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-6">
          {/* Weak Verbs */}
          {report.weak_verbs?.length > 0 && (
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: 0.5 }}
              className="glass rounded-2xl p-6 border border-white/10"
            >
              <div className="flex items-center gap-2 mb-4">
                <Zap size={18} className="text-orange-400" />
                <h2 className="font-display font-semibold text-lg">Strengthen Action Verbs</h2>
              </div>
              <div className="space-y-3">
                {report.weak_verbs.map((item, i) => (
                  <div key={i} className="flex items-center gap-3 text-sm">
                    <span className="text-red-400 line-through bg-red-500/10 px-2.5 py-1 rounded-lg text-xs">
                      {item.original}
                    </span>
                    <span className="text-slate-500">→</span>
                    <span className="text-emerald-400 bg-emerald-500/10 px-2.5 py-1 rounded-lg text-xs font-medium">
                      {item.better}
                    </span>
                  </div>
                ))}
              </div>
            </motion.div>
          )}

          {/* Skills to Add */}
          {report.skills_to_add?.length > 0 && (
            <motion.div
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: 0.5 }}
              className="glass rounded-2xl p-6 border border-white/10"
            >
              <div className="flex items-center gap-2 mb-4">
                <Target size={18} className="text-brand-400" />
                <h2 className="font-display font-semibold text-lg">Recommended Skills</h2>
              </div>
              <div className="flex flex-wrap gap-2">
                {report.skills_to_add.map((skill, i) => (
                  <SkillBadge key={skill} skill={skill} index={i} />
                ))}
              </div>
            </motion.div>
          )}
        </div>

        {/* ── Section Analysis ────────────────────────────────── */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.55 }}
          className="glass rounded-2xl p-6 border border-white/10 mb-6"
        >
          <h2 className="font-display font-semibold text-xl mb-5">Section Analysis</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {Object.entries(report.section_analysis || {}).map(([name, data], i) => (
              <SectionCard key={name} name={name} data={data} index={i} />
            ))}
          </div>
        </motion.div>

        {/* ── Improved Summary ────────────────────────────────── */}
        {report.improved_summary && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.6 }}
            className="glass rounded-2xl p-6 border border-emerald-500/20 bg-emerald-500/5 mb-6"
          >
            <div className="flex items-start gap-3">
              <div className="w-8 h-8 rounded-lg bg-emerald-500/20 flex items-center justify-center shrink-0 mt-0.5">
                <TrendingUp size={16} className="text-emerald-400" />
              </div>
              <div>
                <h2 className="font-display font-semibold text-lg text-emerald-300 mb-2">
                  AI-Improved Professional Summary
                </h2>
                <p className="text-slate-300 text-sm leading-relaxed italic">
                  "{report.improved_summary}"
                </p>
              </div>
            </div>
          </motion.div>
        )}

        {/* Strengths / Issues */}
        {(report.strengths?.length > 0 || report.critical_issues?.length > 0) && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.65 }}
            className="grid grid-cols-1 sm:grid-cols-2 gap-6"
          >
            {report.strengths?.length > 0 && (
              <div className="glass rounded-2xl p-6 border border-white/10">
                <h3 className="font-display font-semibold text-emerald-300 mb-3 flex items-center gap-2">
                  <CheckCircle size={16} /> Strengths
                </h3>
                <ul className="space-y-2">
                  {report.strengths.map((s, i) => (
                    <li key={i} className="text-sm text-slate-300 flex items-start gap-2">
                      <div className="w-1.5 h-1.5 rounded-full bg-emerald-400 shrink-0 mt-1.5" />
                      {s}
                    </li>
                  ))}
                </ul>
              </div>
            )}
            {report.critical_issues?.length > 0 && (
              <div className="glass rounded-2xl p-6 border border-white/10">
                <h3 className="font-display font-semibold text-red-300 mb-3 flex items-center gap-2">
                  <AlertTriangle size={16} /> Critical Issues
                </h3>
                <ul className="space-y-2">
                  {report.critical_issues.map((s, i) => (
                    <li key={i} className="text-sm text-slate-300 flex items-start gap-2">
                      <div className="w-1.5 h-1.5 rounded-full bg-red-400 shrink-0 mt-1.5" />
                      {s}
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </motion.div>
        )}
      </div>
    </div>
  )
}
